name: 构建圣经闹钟应用

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整历史记录以便正确生成版本号
    
    - name: 设置JDK 11并缓存Gradle
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: 设置Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2
    
    - name: 构建Debug APK
      run: gradle assembleDebug
    
    - name: 运行单元测试
      run: gradle testDebugUnitTest
    
    - name: 上传Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: 圣经闹钟-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
    
    - name: 生成Release APK
      run: |
        echo "storeFile=debug.keystore" > keystore.properties
        echo "storePassword=android" >> keystore.properties
        echo "keyAlias=androiddebugkey" >> keystore.properties
        echo "keyPassword=android" >> keystore.properties
        gradle assembleRelease
      
    - name: 上传Release APK
      uses: actions/upload-artifact@v4
      with:
        name: 圣经闹钟-release
        path: app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
    
    - name: 上传测试报告
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: 测试报告
        path: |
          app/build/reports/tests/
          app/build/test-results/
        if-no-files-found: ignore